### ISSUE TITLE
Error during execution docker-compose

### ISSUE THREAD

**Issue by rchemali** [devicehive/devicehive-plugin-cassandra-node#23]
Hello ,
docker-compose does not want to run any solution please ?

> devicehive-plugin-cassandra-node@1.0.0 start /usr/src/app
plugin_1  | > node ./plugin/index.js
plugin_1  |
plugin_1  | Plugin is starting
plugin_1  | /usr/src/app/node_modules/devicehive-plugin-core/src/PluginCore.js:21
plugin_1  |             request(options, (err, response, body) => err || body.error ? reject(err || body.message) : resolve(body));
plugin_1  |                                                                   ^
plugin_1  |
plugin_1  | TypeError: Cannot read property 'error' of undefined

**Comment by Merisho** [comment]
Closing as duplicate (see https://docs.devicehive.com/discuss/5af9a21c74f9be000347573d)
